[package]
name = "imag-diagnostics"
version = "0.9.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-gps command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "../../../build.rs"

[dependencies]
log  = "0.4"
toml = "0.4"
toml-query = "0.6"
indicatif = "0.9"

libimagstore     = { version = "0.9.0", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.9.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.9.0", path = "../../../lib/core/libimagerror" }
libimagentrylink = { version = "0.9.0", path = "../../../lib/entry/libimagentrylink" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["suggestions", "color", "wrap_help"]

