[package]
name = "imag-link"
version = "0.9.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-link command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "../../../build.rs"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.0"
url = "1.5"
toml = "0.4"
toml-query = "0.7"
prettytable-rs = "0.6"

libimagstore     = { version = "0.9.0", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.9.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.9.0", path = "../../../lib/core/libimagerror" }
libimagentrylink = { version = "0.9.0", path = "../../../lib/entry/libimagentrylink" }
libimagutil      = { version = "0.9.0", path = "../../../lib/etc/libimagutil" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dev-dependencies]
env_logger = "0.5"

[dev-dependencies.libimagutil]
version          = "0.9.0"
path = "../../../lib/etc/libimagutil"
default-features = false
features         = ["testing"]

[dev-dependencies.libimagrt]
version          = "0.9.0"
path             = "../../../lib/core/libimagrt"
default-features = false
features         = ["testing"]


