[package]
name = "imag-tag"
version = "0.9.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-tag command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "../../../build.rs"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.0"
toml = "0.4"

libimagstore    = { version = "0.9.0", path = "../../../lib/core/libimagstore" }
libimagrt       = { version = "0.9.0", path = "../../../lib/core/libimagrt" }
libimagerror    = { version = "0.9.0", path = "../../../lib/core/libimagerror" }
libimagentrytag = { version = "0.9.0", path = "../../../lib/entry/libimagentrytag" }
libimagutil     = { version = "0.9.0", path = "../../../lib/etc/libimagutil" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dev-dependencies]
toml-query = "0.7"
env_logger = "0.5"

[dev-dependencies.libimagutil]
version          = "0.9.0"
path             = "../../../lib/etc/libimagutil"
default-features = false
features         = ["testing"]

[dev-dependencies.libimagrt]
version          = "0.9.0"
path             = "../../../lib/core/libimagrt"
default-features = false
features         = ["testing"]

