[package]
name = "imag-category"
version = "0.9.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-category command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "../../../build.rs"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.0"
toml = "0.4"
toml-query = "0.7"

libimagstore           = { version = "0.9.0", path = "../../../lib/core/libimagstore" }
libimagrt              = { version = "0.9.0", path = "../../../lib/core/libimagrt" }
libimagerror           = { version = "0.9.0", path = "../../../lib/core/libimagerror" }
libimagentrycategory   = { version = "0.9.0", path = "../../../lib/entry/libimagentrycategory" }
libimaginteraction     = { version = "0.9.0", path = "../../../lib/etc/libimaginteraction" }

[dependencies.clap]
version          = "^2.29"
default-features = false
features         = ["color", "suggestions", "wrap_help"]

