#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo "No rev list given"
    exit 1
fi

for rev in $(git rev-list $1); do
    if git notes --ref=changelog list $rev &> /dev/null; then
        git log -n 1 --show-notes=* --pretty="format:* %N" $rev
    fi
done
